# Generated by Django 5.2.1 on 2025-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
