# Generated by Django 5.2.1 on 2025-05-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_options_alter_accounts_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
