# Generated by Django 5.2.1 on 2025-05-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accounts_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accounts',
            managers=[
            ],
        ),
    ]
