# Generated by Django 5.2.1 on 2025-05-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accounts_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuserprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
