# Generated by Django 5.2.1 on 2025-05-14 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='note',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
