# Generated by Django 5.2.1 on 2025-05-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_options_alter_accounts_managers_and_more'),
        ('notes', '0002_note_created_at_note_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountuserprofile'),
        ),
    ]
